---
- hosts: dev
  vars:
    user: vagrant
  tasks:
    - name: Install base packages
      sudo: yes
      sudo_user: root
      apt: pkg={{item}} state=installed update-cache=yes
      with_items:
        - build-essential
        - python-dev
        - python-setuptools
        - python-virtualenv
        - python-pip
        - libpq-dev
        - vim
        - tmux
        - htop
        - git
        - libffi-dev
        - libxml2-dev
        - libxslt1-dev
        - curl
      tags:
        - provision

    - name: Install base pip packages
      sudo: yes
      sudo_user: root
      pip: name={{item}}
      with_items:
        - virtualenv
      tags:
        - provision

    - name: Install nvm
      sudo: yes
      sudo_user: "{{user}}"
      shell: >
        curl https://raw.githubusercontent.com/creationix/nvm/v0.8.0/install.sh | sh
        creates=/home/{{user}}/.nvm
      tags:
        - provision

    # Will use .nvmrc in the project folder
    - name: Install node
      sudo: yes
      sudo_user: "{{user}}"
      shell: >
        source ~/.nvm/nvm.sh && nvm install 0.11.13
        chdir=/vagrant
        executable=/bin/bash

    - name: Install bower
      npm: >
        name=bower
        state=present
        global=yes
        executable=/home/vagrant/.nvm/v0.11.13/bin/npm